version: '3.1'
services:
  wordpress:
    image: eugeneware/docker-wordpress-nginx
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./transient-demo:/usr/share/nginx/www/wp-content/plugins/transient-demo

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
